[versions]

compileSdk = "35"
minSdk = "21"
targetSdk = "35"

dagger = "2.56.2"
legacySupportV13 = "1.0.0"
work = "2.10.2"

[libraries]

androidxAppcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
androidxBrowser = { group = "androidx.browser", name = "browser", version = "1.8.0" }
androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version = "1.16.0" }
androidMaterial = { group = "com.google.android.material", name = "material", version = "1.12.0" }
androidxWorkRuntime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
daggerCompiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
daggerAndroid = { group = "com.google.dagger", name = "dagger-android", version.ref = "dagger" }
daggerAndroidProcessor = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version = "2.1.5" }
gradle = { group = "com.android.tools.build", name = "gradle", version = "8.11.0" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.13.1" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version = "2.2.0" }
kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version = "2.2.0" }
legacySupportV13 = { module = "androidx.legacy:legacy-support-v13", version.ref = "legacySupportV13" }
timber = { group = "com.jakewharton.timber", name = "timber", version = "5.0.1" }

[plugins]