[versions]

compileSdk = "35"
minSdk = "21"
targetSdk = "35"
dagger = "2.56.2"

[libraries]

androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version = "1.16.0" }
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
daggerCompiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
daggerAndroid = { group = "com.google.dagger", name = "dagger-android", version.ref = "dagger" }
daggerAndroidProcessor = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version = "2.1.5" }
gradle = { group = "com.android.tools.build", name = "gradle", version = "8.11.0" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.13.1" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version = "2.2.0" }
kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version = "2.2.0" }

[plugins]