[versions]

compileSdk = "35"
minSdk = "21"
targetSdk = "35"

androidxFragment = "1.8.8"
dagger = "2.56.2"
legacySupportV13 = "1.0.0"
okhttp3 = "4.12.0"
work = "2.10.2"

[libraries]

androidxAppcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
androidxBrowser = { group = "androidx.browser", name = "browser", version = "1.8.0" }
androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version = "1.16.0" }
androidxExinterface = { group = "androidx.exifinterface", name = "exifinterface", version = "1.4.1" }
androidFlexbox = { group = "com.google.android.flexbox", name = "flexbox", version = "3.0.0" }
androidxFragment = { group = "androidx.fragment", name = "fragment", version.ref = "androidxFragment" }
androidxFragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidMaterial = { group = "com.google.android.material", name = "material", version = "1.12.0" }
androidxPreference = { group = "androidx.preference", name = "preference", version = "1.2.1" }
androidxWorkRuntime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
commonsIo = { group = "commons-io", name = "commons-io", version = "2.5" } # Commons 2.6+ introduce java.nio usage that we can't access until our minSdkVersion >= 26 (https://developer.android.com/reference/java/io/File#toPath())
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
daggerCompiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
daggerAndroid = { group = "com.google.dagger", name = "dagger-android", version.ref = "dagger" }
daggerAndroidProcessor = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version = "2.1.5" }
gradle = { group = "com.android.tools.build", name = "gradle", version = "8.11.0" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.13.1" }
karumiDexter = { group = "com.karumi", name = "dexter", version = "6.2.3" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version = "2.2.0" }
kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version = "2.2.0" }
legacySupportV13 = { module = "androidx.legacy:legacy-support-v13", version.ref = "legacySupportV13" }
okHttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
okHttpTls = { group = "com.squareup.okhttp3", name = "okhttp-tls", version.ref = "okhttp3" }
okHttpDigest = { group = "io.github.rburgst", name = "okhttp-digest", version = "3.1.1" }
opencsv = { group = "com.opencsv", name = "opencsv", version = "5.11.2" }
osmdroid = { group = "org.osmdroid", name = "osmdroid-android", version = "6.1.20" }
persianJodaTime = { group = "com.github.mohamadian", name = "persianjodatime", version = "1.2" }
playServicesMaps = { group = "com.google.android.gms", name = "play-services-maps", version = "19.2.0" }
playServicesLocation = { group = "com.google.android.gms", name = "play-services-location", version = "20.0.0" }
playServicesAuth = { group = "com.google.android.gms", name = "play-services-auth", version = "20.4.0" }
timber = { group = "com.jakewharton.timber", name = "timber", version = "5.0.1" }

[plugins]