[versions]
dagger = "2.56.2"
[libraries]
gradle = { group = "com.android.tools.build", name = "gradle", version = "8.11.0" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version = "2.2.0" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version = "2.1.5" }
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
daggerCompiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
daggerAndroid = { group = "com.google.dagger", name = "dagger-android", version.ref = "dagger" }
daggerAndroidProcessor = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger" }
[plugins]